#!/bin/bash
# write commit msg without quote
msg=""
opt=""

for word in $@
do
  if [[ $word =~ ^--.+ ]] ; then
    if [[ opt = "" ]] ; then
      opt+="$word"
    else
      opt+=" $word"
    fi
  else
    if [[ msg = "" ]] ; then
      msg+="$word"
    else
      msg+=" $word"
    fi
  fi
done

exec git commit -m "$msg" $opt
